// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
          apiKey: "AIzaSyBB1uFXyTve-YWxmSGDYnBEq70FF8ETC40",
          authDomain: "agrismart-fe804.firebaseapp.com",
          projectId: "agrismart-fe804",
          storageBucket: "agrismart-fe804.appspot.com",
          messagingSenderId: "475432630740",
          appId: "1:475432630740:web:16fcf8e98da245b6dcbe41",
          measurementId: "G-4PKTL1KTCT",
  );

  static const FirebaseOptions android = FirebaseOptions(
          apiKey: "AIzaSyBB1uFXyTve-YWxmSGDYnBEq70FF8ETC40",
          authDomain: "agrismart-fe804.firebaseapp.com",
          projectId: "agrismart-fe804",
          storageBucket: "agrismart-fe804.appspot.com",
          messagingSenderId: "475432630740",
          appId: "1:475432630740:web:16fcf8e98da245b6dcbe41",
          measurementId: "G-4PKTL1KTCT",
  );

  static const FirebaseOptions macos = FirebaseOptions(
          apiKey: "AIzaSyBB1uFXyTve-YWxmSGDYnBEq70FF8ETC40",
          authDomain: "agrismart-fe804.firebaseapp.com",
          projectId: "agrismart-fe804",
          storageBucket: "agrismart-fe804.appspot.com",
          messagingSenderId: "475432630740",
          appId: "1:475432630740:web:16fcf8e98da245b6dcbe41",
          measurementId: "G-4PKTL1KTCT",
  );

  static const FirebaseOptions windows = FirebaseOptions(
          apiKey: "AIzaSyBB1uFXyTve-YWxmSGDYnBEq70FF8ETC40",
          authDomain: "agrismart-fe804.firebaseapp.com",
          projectId: "agrismart-fe804",
          storageBucket: "agrismart-fe804.appspot.com",
          messagingSenderId: "475432630740",
          appId: "1:475432630740:web:16fcf8e98da245b6dcbe41",
          measurementId: "G-4PKTL1KTCT",
  );

}